export const possibleThemes = [
  'Alles',
  'armoedebestrijding ',
  'binnenlandse aangelegenheden ',
  'Brussel ',
  'buitenlands beleid ',
  'cultuur ',
  'economie ',
  'energie ',
  'erfgoed ',
  'financiën ',
  'gelijke kansen ',
  'haven ',
  'inburgering ',
  'innovatie ',
  'jeugd ',
  'landbouw en visserij ',
  'leefmilieu en natuur ',
  'media ',
  'mobiliteit ',
  'natuurlijke rijkdommen ',
  'onderwijs en vorming ',
  'openbare werken ',
  'overheid ',
  'overheidsinvesteringen ',
  'ruimtelijke ordening ',
  'sociale economie ',
  'sport ',
  'tewerkstelling ',
  'toerisme ',
  'Vlaamse Rand ',
  'wetenschap ',
  'welzijn en gezondheid ',
  'wonen ',
  'dierenwelzijn',
];
